### ISSUE TITLE
no docker mvn plugin in the pom

### ISSUE THREAD

**Issue by dadakoko** [carnellj/spmia-chapter1#1]
I m reading your great book about the capabilites of spring with microservices. Using docker is appealing as well but while mvn spring-boot:run shows up the service, mvn clean package docker:build is failing. Would be great to be able to create a docker image already within chapter!

**Comment by carnellj** [comment]
Hi Dadakoko,

I purposely had not built a docker image, for the first chapter because it
was just a simple standalone service with no connections to anything.  It
is simple enough to create a container.  Give me a few days and I will
upload a docker version of the service.  Hope you like the book.

    Thanks,
        John

**Comment by dadakoko** [comment]
thanks a lot for your quick reply!
yes certainly i enjoy your book a lot:-) as a dev with java-spring background i appreciate a lot reading such a clear and well-explained book that demystify creating microservices and highlight associated tools, e.g. docker!
regards
David
