### ISSUE TITLE
typo in readme.md

### ISSUE THREAD

**Issue by freddieFishCake** [carnellj/spmia-chapter1#3]
Current: "Now we are going to use docker-compose to start the actual image. To start the docker image, change to the docker-compose directory in your chapter 1 source code. Issue the following docker-compose command:

docker-compose -f docker/common/docker-compose.yml up"

There isn't a docker-compose directory, and the form of the command looks like you didn't intend to change directory..

**Comment by carnellj** [comment]
Hi,

Thanks for fix.  I am going to post this to errata section on the manning forum.  This will get fixed in any reprint of future books.  Thanks, for catching this.

    - John

**Comment by carnellj** [comment]
https://forums.manning.com/posts/list/0/40971.page#p115756
